######################################################################
# Automatically generated by qmake (2.01a) Wed May 8 11:07:06 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += communicate.h
SOURCES += communicate.cpp main.cpp
