######################################################################
# Automatically generated by qmake (2.01a) Wed May 8 09:57:40 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += practice.cpp
