######################################################################
# Automatically generated by qmake (2.01a) Wed May 8 20:18:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += checkable.h
SOURCES += checkable.cpp main.cpp
