######################################################################
# Automatically generated by qmake (2.01a) Wed May 8 20:54:06 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += toolbar.h
SOURCES += main.cpp toolbar.cpp
