######################################################################
# Automatically generated by qmake (2.01a) Wed May 8 18:50:43 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += anothermenu.cpp main.cpp
