######################################################################
# Automatically generated by qmake (2.01a) Wed May 8 16:09:13 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += simplemenu.h
SOURCES += main.cpp simplemenu.cpp
